export const RECURRING_EXPENSE_TYPES = {
  MISC: "misc",
  SAVINGS: "savings",
  HOUSING: "housing",
  UTILITIES: "utilities",
  SUBSCRIPTIONS: "subscriptions",
  FOOD: "food",
  TRANSPORTATION: "transportation",
  HEALTHCARE: "healthcare",
  INSURANCE: "insurance",
  PHONE: "phone",
  ENTERTAINMENT: "entertainment",
  PERSONAL_CARE: "personal_care",
  DEBT: "debt",
  GIFTS_DONATIONS: "gifts_donations",
  CHILDCARE: "childcare",
  PET_CARE: "pet_care",
  EDUCATION: "education",
  INVEST_GENERAL: "invest_general",
  INVEST_RETIREMENT: "invest_retirement",
};
